lane :test do
	# allure_formatter(
	# 	reportPath: './allure-report', # Provide path to your allure report directory
	# 	pathProvider: lambda { |test| # Provide lambda that returns a path for the given test (given object contains test data from ./allure-report/data/test-cases/*.json)
	# 		# Here I'm using historyId ("TestModule/TestCaseClass/testName()") to return filename
	# 		test['historyId'].split("/")[0..1] # [TestModule, TestCaseClass]
	# 	}
	# )
	allure_formatter_from_docs(
		reportPath: './allure-report', # Provide path to your allure report directory
		testsSourcePath: '/path/to/your/swift/files/with/ui/tests'
	)
	# documentation(
	# 	testsSourcePath: '/path/to/your/swift/files/with/ui/tests',
	# 	output: './allure.docs'
	# )
end
